import { FilterDefinition } from '../interfaces/pc-components.interfaces';

export const COMPONENT_FILTER_SCHEMAS: Record<
  string,
  Record<string, FilterDefinition>
> = {
  'pc-case': {
    width: { field: 'width', type: 'range' },
    height: { field: 'height', type: 'range' },
    depth: { field: 'depth', type: 'range' },
    maxVideoCardLenght: { field: 'max_video_card_length', type: 'range' },
    maxCpuCoolerHeight: { field: 'max_cpu_cooler_height', type: 'range' },
    manufacturer: { field: 'manufacturer', type: 'multi-string' },
    formFactor: { field: 'form_factor', type: 'multi-string' },
  },
  'cpu-cooler': {
    fanQuantity: { field: 'fan_quantity', type: 'range' },
    height: { field: 'height', type: 'range' },
    radiatorSize: { field: 'radiator_size', type: 'range' },
    minFanRpm: { field: 'min_fan_rpm', type: 'range' },
    maxFanRpm: { field: 'max_fan_rpm', type: 'range' },
    manufacturer: { field: 'manufacturer', type: 'multi-string' },
    waterCooled: { field: 'water_cooled', type: 'boolean' },
  },
  cpu: {
    coreCount: { field: 'core_count', type: 'range' },
    threadCount: { field: 'thread_count', type: 'range' },
    baseClock: { field: 'base_clock', type: 'range' },
    boostClock: { field: 'boost_clock', type: 'range' },
    tdp: { field: 'tdp', type: 'range' },
    maxSupportedMemory: { field: 'max_supported_memory', type: 'range' },
    socket: { field: 'socket', type: 'multi-string' },
    manufacturer: { field: 'manufacturer', type: 'multi-string' },
    microarchitecture: { field: 'microarchitecture', type: 'multi-string' },
    coreFamily: { field: 'core_family', type: 'multi-string' },
    integratedGraphics: { field: 'integrated_graphics', type: 'multi-string' },
    eccSupport: { field: 'ecc_support', type: 'boolean' },
    includesCooler: { field: 'includes_cooler', type: 'boolean' },
    simultaneousMultithreading: {
      field: 'simultaneous_multithreading',
      type: 'boolean',
    },
  },
  fan: {
    quantity: { field: 'quantity', type: 'range' },
    minAirflow: { field: 'min_airflow', type: 'range' },
    maxAirflow: { field: 'max_airflow', type: 'range' },
    manufacturer: { field: 'manufacturer', type: 'multi-string' },
    controller: { field: 'controller', type: 'multi-string' },
    flowDirection: { field: 'flow_direction', type: 'multi-string' },
  },
  gpu: {
    memory: { field: 'memory', type: 'range' },
    coreBaseClock: { field: 'core_base_clock', type: 'range' },
    coreBoostClock: { field: 'core_boost_clock', type: 'range' },
    memoryBus: { field: 'memory_bus', type: 'range' },
    length: { field: 'length', type: 'range' },
    tdp: { field: 'tdp', type: 'range' },
    pcie6Pin: { field: 'pcie_6_pin', type: 'range' },
    pcie8Pin: { field: 'pcie_8_pin', type: 'range' },
    pcie12VHPWR: { field: 'pcie_12vhpwr', type: 'range' },
    pcie12V2x6: { field: 'pcie_12v_2x6', type: 'range' },
    hdmi21: { field: 'hdmi_2_1', type: 'range' },
    hdmi20: { field: 'hdmi_2_0', type: 'range' },
    displayPort21: { field: 'displayport_2_1', type: 'range' },
    displayPort21a: { field: 'displayport_2_1a', type: 'range' },
    displayPort14a: { field: 'displayport_1_4a', type: 'range' },
    manufacturer: { field: 'manufacturer', type: 'multi-string' },
    chipset: { field: 'chipset', type: 'multi-string' },
    memoryType: { field: 'memory_type', type: 'multi-string' },
    gpuInterface: { field: 'gpu_interface', type: 'multi-string' },
  },
  keyboard: {
    manufacturer: { field: 'manufacturer', type: 'multi-string' },
  },
  monitor: {
    horizontalRes: { field: 'horizontal_res', type: 'range' },
    verticalRes: { field: 'vertical_res', type: 'range' },
    refreshRate: { field: 'refresh_rate', type: 'range' },
    responseTime: { field: 'response_time', type: 'range' },
    screenSize: { field: 'screen_size', type: 'range' },
    manufacturer: { field: 'manufacturer', type: 'multi-string' },
    panelType: { field: 'panel_type', type: 'multi-string' },
  },
  motherboard: {
    maxMemory: { field: 'max_memory', type: 'range' },
    memorySlots: { field: 'memory_slots', type: 'range' },
    m2SlotCount: { field: 'm2_slot_count', type: 'range' },
    pcieSlotCount: { field: 'pcie_slot_count', type: 'range' },
    manufacturer: { field: 'manufacturer', type: 'multi-string' },
    socket: { field: 'socket', type: 'multi-string' },
    ramType: { field: 'ram_type', type: 'multi-string' },
    formFactor: { field: 'form_factor', type: 'multi-string' },
    chipset: { field: 'chipset', type: 'multi-string' },
    biosFlashback: { field: 'bios_flashback', type: 'boolean' },
    biosClearCmos: { field: 'bios_clear_cmos', type: 'boolean' },
    eccSupport: { field: 'ecc_support', type: 'boolean' },
    raidSupport: { field: 'raid_support', type: 'boolean' },
  },
  mouse: {
    manufacturer: { field: 'manufacturer', type: 'multi-string' },
  },
  'power-supply': {
    wattage: { field: 'wattage', type: 'range' },
    eps8Pin: { field: 'eps_8_pin', type: 'range' },
    pcie12Vhpwr: { field: 'pcie_12vhpwr', type: 'range' },
    pcie6Plus2Pin: { field: 'pcie_6_plus_2_pin', type: 'range' },
    sata: { field: 'sata', type: 'range' },
    manufacturer: { field: 'manufacturer', type: 'multi-string' },
    efficencyRating: { field: 'efficency_rating', type: 'multi-string' },
    formFactor: { field: 'form_factor', type: 'multi-string' },
  },
  ram: {
    quantity: { field: 'quantity', type: 'range' },
    capacity: { field: 'capacity', type: 'range' },
    speed: { field: 'speed', type: 'range' },
    casLatency: { field: 'cas_latency', type: 'range' },
    voltage: { field: 'voltage', type: 'range' },
    memoryType: { field: 'memory_type', type: 'multi-string' },
    formFactor: { field: 'form_factor', type: 'multi-string' },
    manufacturer: { field: 'manufacturer', type: 'multi-string' },
    heatSpreader: { field: 'heat_spreader', type: 'boolean' },
    ecc: { field: 'ecc', type: 'boolean' },
  },
  'storage-drive': {
    capacity: { field: 'capacity', type: 'range' },
    manufacturer: { field: 'manufacturer', type: 'multi-string' },
    storageType: { field: 'storage_type', type: 'multi-string' },
    formFactor: { field: 'form_factor', type: 'multi-string' },
    storageInterface: { field: 'storage_interface', type: 'multi-string' },
    nvme: { field: 'nvme', type: 'boolean' },
  },
};
