export const bool = (v: unknown) => (v === true ? 'Yes' : v === false ? 'No' : '—');
export const num  = (v: unknown) => (v != null ? String(v) : '—');
export const str  = (v: unknown) => (v != null && v !== '' ? String(v) : '—');
export const arr  = (v: unknown) => Array.isArray(v) && v.length > 0 ? (v as string[]).join('\n') : '—';
export const ghz  = (v: unknown) => (v != null ? `${v} GHz` : '—');
export const mb   = (v: unknown) => (v != null ? `${v} MB` : '—');
export const gb   = (v: unknown) => (v != null ? `${v} GB` : '—');
export const w    = (v: unknown) => (v != null ? `${v} W` : '—');
export const mm   = (v: unknown) => (v != null ? `${v} mm` : '—');
export const rpm  = (v: unknown) => (v != null ? `${v} RPM` : '—');
export const db   = (v: unknown) => (v != null ? `${v} dB` : '—');
export const mhz  = (v: unknown) => (v != null ? `${v} MHz` : '—');
export const hz   = (v: unknown) => (v != null ? `${v} Hz` : '—');
export const ms   = (v: unknown) => (v != null ? `${v} ms` : '—');
export const inch = (v: unknown) => (v != null ? `${v}"` : '—');
export const kg   = (v: unknown) => (v != null ? `${v} kg` : '—');
export const liter = (v: unknown) => (v != null ? `${v} L` : '—');
export const cfm  = (v: unknown) => (v != null ? `${v} CFM` : '—');
export const mmhgo = (v: unknown) => (v != null ? `${v} mmH₂O` : '—');
export const v_   = (v: unknown) => (v != null ? `${v} V` : '—');