import type { AttrDef } from "../types/PcComponentDetails.types";
import { arr, bool, cfm, db, gb, ghz, hz, inch, kg, liter, mb, mhz, mm, mmhgo, ms, num, rpm, str, v_, w } from "./PcComponentAttributeFormatters";

export const BASE_ATTRS: AttrDef[] = [
  { key: 'manufacturer', label: 'Manufacturer', format: str,
    description: 'The company that designed and produced this component.' },
  { key: 'series', label: 'Series', format: str,
    description: 'The product line or family this component belongs to within the manufacturer\'s lineup.' },
  { key: 'variant', label: 'Variant', format: str,
    description: 'A specific version or revision of this model.' },
  { key: 'releaseYear', label: 'Release Year', format: num,
    description: 'The year this component was officially released to the market.' },
];

export const COMPONENT_ATTRS: Record<string, AttrDef[]> = {
  cpu: [
    ...BASE_ATTRS,
    { key: 'socket', label: 'Socket', format: str,
      description: 'The physical interface used to connect the CPU to the motherboard. Must match the motherboard socket.' },
    { key: 'coreCount', label: 'Total Cores', format: num,
      description: 'The number of independent processing units. More cores allow better multitasking and parallel workloads.' },
    { key: 'threadCount', label: 'Threads', format: num,
      description: 'The number of logical threads the CPU can handle, which are the smallest sequence of programmed instructions that a processor core can manage independently.' },
    { key: 'baseClock', label: 'Base Clock', format: ghz,
      description: 'The guaranteed minimum operating frequency of a CPU under sustained load.' },
    { key: 'boostClock', label: 'Boost Clock', format: ghz,
      description: 'The maximum operating frequency the CPU can reach under favorable thermal conditions.' },
    { key: 'tdp', label: 'TDP', format: w,
      description: 'Thermal Design Power. The maximum amount of heat a CPU generates when operating at its base frequency. It indicates the minimun heat dissipation capacity required for the cooler.' },
    { key: 'microarchitecture', label: 'Microarchitecture', format: str,
      description: 'The underlying design and organization of the processors\'s core logic.' },
    { key: 'coreFamily', label: 'Core Family', format: str,
      description: 'The specific group of CPUs with which this CPU shares a common architecture and design features.' },
    { key: 'integratedGraphics', label: 'Integrated Graphics', format: str,
      description: 'A GPU built into the processor. Needed to display graphics when a GPU isn\'t installed.' },
    { key: 'cachel1', label: 'Cache L1', format: str,
      description: 'The fastest and smallest cache tier, private to each core. Reduces latency for frequently accessed data.' },
    { key: 'cachel2', label: 'Cache L2', format: mb,
      description: 'Second-level cache, larger but slightly slower than L1. Acts as a buffer between L1 and L3.' },
    { key: 'cachel3', label: 'Cache L3', format: mb,
      description: 'The largest on-chip cache, shared across cores. Large L3 greatly benefits gaming and latency-sensitive workloads.' },
    { key: 'maxSupportedMemory', label: 'Max Supported Memory', format: gb,
      description: 'The maximum total RAM capacity the CPU memory controller supports.' },
    { key: 'supportedMemoryTypes', label: 'Supported Memory Types', format: arr,
      description: 'The RAM standards this CPU\'s memory controller is compatible with.' },
    { key: 'eccSupport', label: 'ECC Support', format: bool,
      description: 'Error-Correcting Code memory support. Detects and corrects single-bit memory errors, important for workstations and servers.' },
    { key: 'includesCooler', label: 'Includes Cooler', format: bool,
      description: 'Whether a CPU cooler is included in the box.' },
    { key: 'simultaneousMultithreading', label: 'Simultaneous Multithreading', format: bool,
      description: 'Whether the CPU supports simultaneous multithreading. It\'s a technology that allows a single physical core to manage and execute multiple threads simultaneously (also known as hyperthreading).' },
  ],

  gpu: [
    ...BASE_ATTRS,
    { key: 'chipset', label: 'Chipset', format: str,
      description: 'The core processor of a GPU, responsible for all rendering calculations.' },
    { key: 'memory', label: 'Memory', format: gb,
      description: 'The amount of dedicated video RAM (VRAM). More VRAM is required for higher resolutions and larger textures.' },
    { key: 'memoryType', label: 'Memory Type', format: str,
      description: 'The VRAM technology. Affects bandwidth and power efficiency.' },
    { key: 'memoryBus', label: 'Memory Bus', format: (v) => (v != null ? `${v}-bit` : '—'),
      description: 'The width of the data path between the GPU and VRAM. Wider buses allow higher memory bandwidth.' },
    { key: 'coreBaseClock', label: 'Core Base Clock', format: ghz,
      description: 'The minimum guaranteed GPU core frequency under load.' },
    { key: 'coreBoostClock', label: 'Core Boost Clock', format: ghz,
      description: 'The maximum GPU core frequency achievable under favorable thermal and power conditions.' },
    { key: 'effectiveMemoryClock', label: 'Effective Memory Clock', format: ghz,
      description: 'The effective data rate of the VRAM after accounting for DDR multipliers.' },
    { key: 'tdp', label: 'TDP', format: w,
      description: 'Thermal Design Power. The maximum amount of heat a GPU generates when operating at its base frequency. It can also be used as an estimate of its maximum power consumption.' },
    { key: 'length', label: 'Length', format: mm,
      description: 'Physical card length.' },
    { key: 'gpuInterface', label: 'Interface', format: str,
      description: 'The motherboard slot type this GPU uses.' },
    { key: 'pcie6Pin', label: 'PCIe 6-pin Connectors', format: num,
      description: 'Number of 6-pin PCIe power connectors required from the PSU.' },
    { key: 'pcie8Pin', label: 'PCIe 8-pin Connectors', format: num,
      description: 'Number of 8-pin PCIe power connectors required from the PSU.' },
    { key: 'pcie12VHPWR', label: 'PCIe 12VHPWR Connectors', format: num,
      description: 'Number of 16-pin 12VHPWR connectors required. Used on high-end NVIDIA Ada cards.' },
    { key: 'pcie12V2x6', label: 'PCIe 12V-2x6 Connectors', format: num,
      description: 'Number of 12V-2x6 connectors required. The updated safer standard replacing 12VHPWR.' },
    { key: 'hdmi21', label: 'HDMI 2.1 Outputs', format: num,
      description: 'Number of HDMI 2.1 ports. Supports up to 4K 144Hz or 8K 60Hz with DSC.' },
    { key: 'hdmi20', label: 'HDMI 2.0 Outputs', format: num,
      description: 'Number of HDMI 2.0 ports. Supports up to 4K 60Hz.' },
    { key: 'displayPort21', label: 'DisplayPort 2.1 Outputs', format: num,
      description: 'Number of DisplayPort 2.1 ports. Supports up to 16K or 4K 480Hz.' },
    { key: 'displayPort21a', label: 'DisplayPort 2.1a Outputs', format: num,
      description: 'Number of DisplayPort 2.1a ports, the latest revision with improved power delivery.' },
    { key: 'displayPort14a', label: 'DisplayPort 1.4a Outputs', format: num,
      description: 'Number of DisplayPort 1.4a ports. Supports up to 8K 30Hz or 4K 120Hz with DSC.' },
    { key: 'dvid', label: 'DVI-D Outputs', format: num,
      description: 'Number of DVI-D ports. A legacy digital video connector, rarely used on modern monitors.' },
    { key: 'vga', label: 'VGA Outputs', format: num,
      description: 'Number of VGA ports. An analog legacy connector, found only on very old or budget hardware.' },
  ],

  motherboard: [
    ...BASE_ATTRS,
    { key: 'socket', label: 'Socket', format: str,
      description: 'The physical interface used to connect the motherboard to the CPU. Must match the CPU socket.' },
    { key: 'chipset', label: 'Chipset', format: str,
      description: 'Controls communication between the CPU, RAM, storage, and peripherals. Higher-end chipsets offer more features and overclocking support.' },
    { key: 'formFactor', label: 'Form Factor', format: str,
      description: 'The physical size standard of the board.' },
    { key: 'ramType', label: 'RAM Type', format: str,
      description: 'The RAM memory standard supported.' },
    { key: 'maxMemory', label: 'Max Memory', format: gb,
      description: 'The maximum total RAM capacity the board can address across all slots.' },
    { key: 'memorySlots', label: 'Memory Slots', format: num,
      description: 'Number of physical RAM slots. More slots allow greater capacity and dual/quad-channel configurations.' },
    { key: 'sata6GbSPorts', label: 'SATA 6 Gb/s Ports', format: num,
      description: 'Number of SATA III ports for connecting HDDs, SSDs, and optical drives at up to 600 MB/s.' },
    { key: 'sata3GbSPorts', label: 'SATA 3 Gb/s Ports', format: num,
      description: 'Number of legacy SATA II ports, limited to 300 MB/s. Rarely present on modern boards.' },
    { key: 'u2Ports', label: 'U.2 Ports', format: num,
      description: 'Number of U.2 (SFF-8639) ports for enterprise NVMe SSDs using a SATA-style connector.' },
    { key: 'm2SlotCount', label: 'M.2 Slots', format: num,
      description: 'Number of M.2 slots for compact NVMe or SATA SSDs.' },
    { key: 'pcieSlotCount', label: 'PCIe Slots', format: num,
      description: 'Total number of PCIe expansion slots for GPUs, capture cards, and other add-in cards.' },
    { key: 'usb20Headers', label: 'USB 2.0 Headers', format: num,
      description: 'Internal headers for connecting front-panel USB 2.0 ports on the case.' },
    { key: 'usb32Gen1Headers', label: 'USB 3.2 Gen 1 Headers', format: num,
      description: 'Internal headers for front-panel USB 3.2 Gen 1 ports.' },
    { key: 'usb32Gen2Headers', label: 'USB 3.2 Gen 2 Headers', format: num,
      description: 'Internal headers for front-panel USB 3.2 Gen 2 ports.' },
    { key: 'usb32Gen2x2Headers', label: 'USB 3.2 Gen 2×2 Headers', format: num,
      description: 'Internal headers for front-panel USB 3.2 Gen 2×2 Type-C ports.' },
    { key: 'usb4Headers', label: 'USB 4 Headers', format: num,
      description: 'Internal headers for front-panel USB 4 Type-C ports.' },
    { key: 'onboardEthernet', label: 'Onboard Ethernet', format: str,
      description: 'The integrated LAN controller and its maximum speed.' },
    { key: 'wirelessNetworking', label: 'Wireless Networking', format: str,
      description: 'Integrated Wi-Fi and Bluetooth standard.' },
    { key: 'audio', label: 'Audio', format: str,
      description: 'The onboard audio codec. Determines audio quality.' },
    { key: 'backPanelPorts', label: 'Back Panel Ports', format: arr,
      description: 'The I/O ports available on the rear of the motherboard, such as USB, video, audio, and ethernet.' },
    { key: 'biosFlashback', label: 'BIOS Flashback', format: bool,
      description: 'Allows flashing the BIOS using only a USB drive and PSU power, without a CPU or RAM installed.' },
    { key: 'biosClearCmos', label: 'BIOS Clear CMOS', format: bool,
      description: 'A dedicated button or jumper to reset BIOS settings to factory defaults, useful after a failed overclock.' },
    { key: 'eccSupport', label: 'ECC Support', format: bool,
      description: 'Support for Error-Correcting Code RAM, which detects and corrects memory errors.' },
    { key: 'raidSupport', label: 'RAID Support', format: bool,
      description: 'Ability to configure multiple storage drives in RAID arrays for redundancy or performance.' },
    { key: 'backConnect', label: 'Back Connect', format: bool,
      description: 'All internal connectors are routed to the rear of the motherboard tray, enabling completely cable-free front aesthetics.' },
  ],

  ram: [
    ...BASE_ATTRS,
    { key: 'memoryType', label: 'Memory Type', format: str,
      description: 'The DDR generation. Must match what the motherboard and CPU support.' },
    { key: 'formFactor', label: 'Form Factor', format: str,
      description: 'Physical module size: DIMM for desktops, SO-DIMM for laptops and small-form-factor builds.' },
    { key: 'quantity', label: 'Quantity', format: num,
      description: 'Number of modules included in the kit. Two sticks enable dual-channel for better bandwidth.' },
    { key: 'capacity', label: 'Capacity', format: gb,
      description: 'The total capacity across all individual cards.' },
    { key: 'speed', label: 'Speed', format: mhz,
      description: 'The rated operating frequency. Higher speeds improve bandwidth.' },
    { key: 'casLatency', label: 'CAS Latency', format: (v) => (v != null ? `CL${v}` : '—'),
      description: 'The number of clock cycles between a memory request and the data being available. Lower is better at the same frequency.' },
    { key: 'timings', label: 'Timings', format: str,
      description: 'The complete timing specification ot the RAM, (CAS Latency)-(RAS to CAS Delay)-(RAS Precharge)-(Active to Precharge Delay).' },
    { key: 'voltage', label: 'Voltage', format: v_,
      description: 'Operating voltage of the RAM. Higher voltages may allow faster speeds but generate more heat.' },
    { key: 'heatSpreader', label: 'Heat Spreader', format: bool,
      description: 'A metal heatsink attached to the module to dissipate heat and improve sustained performance.' },
    { key: 'rgb', label: 'RGB', format: bool,
      description: 'Whether the module includes RGB lighting, controllable via motherboard software.' },
    { key: 'ecc', label: 'ECC', format: bool,
      description: 'Error-Correcting Code memory. Detects and corrects single-bit errors. Requires ECC-capable CPU and motherboard.' },
  ],

  'storage-drive': [
    ...BASE_ATTRS,
    { key: 'storageType', label: 'Type', format: str,
      description: 'The storage drive technology.' },
    { key: 'formFactor', label: 'Form Factor', format: str,
      description: 'Physical size standard. Determines which slots or bays it fits.' },
    { key: 'storageInterface', label: 'Interface', format: str,
      description: 'The connection protocol. PCIe NVMe drives are significantly faster than SATA.' },
    { key: 'capacity', label: 'Capacity', format: gb,
      description: 'Total storage capacity of the drive.' },
    { key: 'nvme', label: 'NVMe', format: bool,
      description: 'Non-Volatile Memory Express. a protocol optimized for SSDs over PCIe. Offers much lower latency than AHCI/SATA.' },
  ],

  'cpu-cooler': [
    ...BASE_ATTRS,
    { key: 'waterCooled', label: 'Water Cooled', format: bool,
      description: 'Whether this is an All-in-One liquid cooler. Liquid cooling generally outperforms air cooling.' },
    { key: 'fanless', label: 'Fanless', format: bool,
      description: 'A passive cooler with no moving parts. Completely silent but limited to low-TDP CPUs.' },
    { key: 'fanSize', label: 'Fan Size', format: mm,
      description: 'Diameter of the included fan(s).' },
    { key: 'fanQuantity', label: 'Fan Quantity', format: num,
      description: 'Number of fans included. Dual-fan towers or push-pull configurations improve airflow.' },
    { key: 'minFanRpm', label: 'Min Fan RPM', format: rpm,
      description: 'Lowest fan speed, typically at idle. Lower minimum RPM means quieter operation when the system is not under load.' },
    { key: 'maxFanRpm', label: 'Max Fan RPM', format: rpm,
      description: 'Maximum fan speed under full load. Higher RPM increases cooling but also noise.' },
    { key: 'minNoiseLevel', label: 'Min Noise Level', format: db,
      description: 'Sound output at minimum fan speed, measured in decibels.' },
    { key: 'maxNoiseLevel', label: 'Max Noise Level', format: db,
      description: 'Sound output at maximum fan speed. Relevant for sustained heavy workloads.' },
    { key: 'height', label: 'Height', format: mm,
      description: 'Total cooler height.' },
    { key: 'radiatorSize', label: 'Radiator Size', format: mm,
      description: 'For liquid coolers, the radiator length in mm.' },
    { key: 'supportedSockets', label: 'Supported Sockets', format: arr,
      description: 'List of CPU sockets this cooler is compatible with.' },
  ],

  case: [
    ...BASE_ATTRS,
    { key: 'formFactor', label: 'Form Factor', format: str,
      description: 'Case size category.' },
    { key: 'supportedMotherboardFormFactors', label: 'Supported Motherboard Form Factors', format: arr,
      description: 'List of motherboard sizes that fit inside this case.' },
    { key: 'width', label: 'Width', format: mm,
      description: 'External width of the case.' },
    { key: 'height', label: 'Height', format: mm,
      description: 'External height of the case.' },
    { key: 'depth', label: 'Depth', format: mm,
      description: 'External depth of the case.' },
    { key: 'volume', label: 'Volume', format: liter,
      description: 'Internal volume in liters.' },
    { key: 'weight', label: 'Weight', format: kg,
      description: 'Weight of the empty case.' },
    { key: 'maxVideoCardLength', label: 'Max GPU Length', format: mm,
      description: 'Maximum GPU length this case can accommodate.' },
    { key: 'maxCpuCoolerHeight', label: 'Max CPU Cooler Height', format: mm,
      description: 'Maximum height for air CPU coolers.' },
    { key: 'internal35bays', label: 'Internal 3.5" Bays', format: num,
      description: 'Number of 3.5" drive bays for full-size HDDs.' },
    { key: 'internal25bays', label: 'Internal 2.5" Bays', format: num,
      description: 'Number of 2.5" bays for SSDs or slim HDDs.' },
    { key: 'expansionSlots', label: 'Expansion Slots', format: num,
      description: 'Number of rear PCIe expansion slot covers for add-in cards.' },
    { key: 'riserExpansionSlots', label: 'Riser Expansion Slots', format: num,
      description: 'Expansion slots accessible via a riser cable for vertical GPU mounting.' },
    { key: 'sidePanel', label: 'Side Panel', format: str,
      description: 'Side panel material. Tempered glass allows viewing the internal components.' },
    { key: 'powerSupply', label: 'Included PSU', format: str,
      description: 'Whether a power supply is bundled.' },
    { key: 'powerSupplyShroud', label: 'PSU Shroud', format: bool,
      description: 'A cover that hides the power supply and cable clutter in the lower chamber for a cleaner look.' },
    { key: 'frontUsbPorts', label: 'Front USB Ports', format: arr,
      description: 'USB ports available on the front I/O panel of the case for convenient device access.' },
  ],

  'power-supply': [
    ...BASE_ATTRS,
    { key: 'formFactor', label: 'Form Factor', format: str,
      description: 'Physical size standard of the PSU.' },
    { key: 'wattage', label: 'Wattage', format: w,
      description: 'Maximum continuous power output.' },
    { key: 'efficencyRating', label: 'Efficiency Rating', format: str,
      description: '80+ certification tier. Higher ratings mean less wasted energy as heat.' },
    { key: 'modular', label: 'Modular', format: str,
      description: 'Full-modular PSUs let you remove all unused cables. Semi-modular keep the main cables fixed. Non-modular have all cables permanently attached.' },
    { key: 'fanless', label: 'Fanless', format: bool,
      description: 'A passive PSU with no fan. Completely silent but requires adequate case airflow to stay cool.' },
    { key: 'length', label: 'Length', format: mm,
      description: 'Physical length of the PSU. Some cases have limited PSU clearance, especially SFF builds.' },
    { key: 'eps8Pin', label: 'EPS 8-pin Connectors', format: num,
      description: 'CPU power connectors. High-end boards may require two EPS connectors.' },
    { key: 'pcie12Vhpwr', label: 'PCIe 12VHPWR Connectors', format: num,
      description: 'Single 16-pin connector for high-end GPUs.' },
    { key: 'pcie6Plus2Pin', label: 'PCIe 6+2-pin Connectors', format: num,
      description: 'Standard GPU power connectors, configurable as 6-pin or 8-pin.' },
    { key: 'sata', label: 'SATA Connectors', format: num,
      description: 'Power connectors for SATA HDDs, SSDs, and optical drives.' },
  ],

  fan: [
    ...BASE_ATTRS,
    { key: 'quantity', label: 'Quantity', format: num,
      description: 'Number of fans included in the pack.' },
    { key: 'size', label: 'Size', format: mm,
      description: 'Fan diameter.' },
    { key: 'connector', label: 'Connector', format: str,
      description: 'How the fan connects to the motherboard.' },
    { key: 'controller', label: 'Controller', format: str,
      description: 'Whether a fan hub or controller is included for managing multiple fans from a single header.' },
    { key: 'led', label: 'LED', format: str,
      description: 'Lighting type.' },
    { key: 'flowDirection', label: 'Flow Direction', format: str,
      description: 'Standard draws cool air in. Reverse pushes warm air out.' },
    { key: 'pwm', label: 'PWM', format: bool,
      description: 'Pulse Width Modulation allows the motherboard to precisely control fan speed for noise/performance balance.' },
    { key: 'minNoiseLevel', label: 'Min Noise Level', format: db,
      description: 'Sound output at minimum fan speed, measured in decibels.' },
    { key: 'maxNoiseLevel', label: 'Max Noise Level', format: db,
      description: 'Sound output at maximum fan speed. Relevant for sustained heavy workloads.' },
    { key: 'minAirflow', label: 'Min Airflow', format: cfm,
      description: 'Cubic Feet per Minute at minimum speed. Indicates how much air the fan moves at idle.' },
    { key: 'maxAirflow', label: 'Max Airflow', format: cfm,
      description: 'Maximum airflow at full speed. Higher CFM improves case ventilation.' },
    { key: 'staticPressure', label: 'Static Pressure', format: mmhgo,
      description: 'Resistance to airflow. High static pressure fans are better for radiators and dense heatsinks.' },
  ],

  monitor: [
    ...BASE_ATTRS,
    { key: 'screenSize', label: 'Screen Size', format: inch,
      description: 'Diagonal screen size. Larger screens benefit from higher resolutions to maintain sharpness.' },
    { key: 'panelType', label: 'Panel Type', format: str,
      description: 'IPS: best colors and viewing angles. TN: fastest response. VA: best contrast. OLED: perfect blacks. etc.' },
    { key: 'horizontalRes', label: 'Horizontal Resolution', format: (v) => (v != null ? `${v}px` : '—'),
      description: 'Number of pixels horizontally.' },
    { key: 'verticalRes', label: 'Vertical Resolution', format: (v) => (v != null ? `${v}px` : '—'),
      description: 'Number of pixels vertically.' },
    { key: 'aspectRatio', label: 'Aspect Ratio', format: str,
      description: 'Width-to-height ratio.' },
    { key: 'refreshRate', label: 'Refresh Rate', format: hz,
      description: 'How many frames the monitor displays per second. Higher rates feel smoother in fast-paced games.' },
    { key: 'responseTime', label: 'Response Time', format: ms,
      description: 'Time for a pixel to change color. Lower values reduce motion blur and ghosting.' },
    { key: 'maxBrightness', label: 'Max Brightness', format: str,
      description: 'Peak luminance. Higher brightness improves HDR and visibility in well-lit environments.' },
    { key: 'adaptiveSync', label: 'Adaptive Sync', format: str,
      description: 'Synchronizes the monitor refresh rate with the GPU frame rate to eliminate screen tearing.' },
    { key: 'connectors', label: 'Connectors', format: str,
      description: 'Video input ports available on the monitor.' },
  ],

  keyboard: [...BASE_ATTRS],
  mouse: [...BASE_ATTRS],
};